SELECT 
    B.AUTHOR_ID AS AUTHOR_ID,
    A.AUTHOR_NAME AS AUTHOR_NAME,
    B.CATEGORY AS CATEGORY,
    SUM(B.PRICE*BS.SALES) AS TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A
ON B.AUTHOR_ID=A.AUTHOR_ID
INNER JOIN BOOK_SALES BS
ON B.BOOK_ID=BS.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m')='2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
