# SELECT
#    FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (FOOD_TYPE, FAVORITES) IN (
#     SELECT FOOD_TYPE, MAX(FAVORITES)
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE
# )
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC;

SELECT
   FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R
WHERE R.FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO S
    WHERE S.FOOD_TYPE=R.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;
