SELECT 
    C.CAR_ID AS CAR_ID,
    C.CAR_TYPE AS CAR_TYPE,
    ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE
    C.CAR_ID NOT IN (
        SELECT CH.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
        WHERE CH.END_DATE>='2022-11-01' AND CH.START_DATE<='2022-11-30'
    )
AND (C.CAR_TYPE='세단' OR C.CAR_TYPE='SUV')
AND ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) >= 500000 -- 대여 금액 조건
AND ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) < 2000000 -- 대여 금액 조건
AND P.DURATION_TYPE LIKE '30%'
GROUP BY C.CAR_ID, C.CAR_TYPE
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
